// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { FileTransferGenerateUrlData, FileTransferGenerateUrlResponse, FileTransferValidateUrlRouteData, FileTransferValidateUrlRouteResponse, FileTransferLoginAccessTokenData, FileTransferLoginAccessTokenResponse, FileTransferUploadFileData, FileTransferUploadFileResponse, FileTransferListFilesResponse } from './types.gen';

export class FileTransferService {
    /**
     * Generate Url
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ResponseURL Successful Response
     * @throws ApiError
     */
    public static generateUrl(data: FileTransferGenerateUrlData): CancelablePromise<FileTransferGenerateUrlResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/file-transfer/generate-url',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Validate Url Route
     * When the customer first clicks the URL, this route validates the token.
     * @param data The data for the request.
     * @param data.token
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static validateUrlRoute(data: FileTransferValidateUrlRouteData): CancelablePromise<FileTransferValidateUrlRouteResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/file-transfer/validate-url',
            query: {
                token: data.token
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: FileTransferLoginAccessTokenData): CancelablePromise<FileTransferLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/file-transfer/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Upload File
     * @param data The data for the request.
     * @param data.formData
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static uploadFile(data: FileTransferUploadFileData): CancelablePromise<FileTransferUploadFileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/file-transfer/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Files
     * @returns S3Object Successful Response
     * @throws ApiError
     */
    public static listFiles(): CancelablePromise<FileTransferListFilesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/file-transfer/files'
        });
    }
    
}