// This file is auto-generated by @hey-api/openapi-ts

export type Body_file_transfer___login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_file_transfer___upload_file = {
    file: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type PromptURL = {
    company_name: string;
    expiry_hours: number;
    type: 'download' | 'upload';
};

export type type = 'download' | 'upload';

export type ResponseURL = {
    url: string;
    username: string;
    password: string;
};

export type S3Object = {
    Key: string;
    LastModified: string;
    Size: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type FileTransferGenerateUrlData = {
    requestBody: PromptURL;
};

export type FileTransferGenerateUrlResponse = (ResponseURL);

export type FileTransferValidateUrlRouteData = {
    token: string;
};

export type FileTransferValidateUrlRouteResponse = (boolean);

export type FileTransferLoginAccessTokenData = {
    formData: Body_file_transfer___login_access_token;
};

export type FileTransferLoginAccessTokenResponse = (Token);

export type FileTransferUploadFileData = {
    formData: Body_file_transfer___upload_file;
};

export type FileTransferUploadFileResponse = (Message);

export type FileTransferListFilesResponse = (Array<S3Object>);