// This file is auto-generated by @hey-api/openapi-ts

export type Body_upload___login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_upload___upload_file = {
    file: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type PromptURL = {
    company_name: string;
    expiry_minutes: number;
};

export type ResponseURL = {
    url: string;
    username: string;
    password: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type UploadGenerateUrlData = {
    requestBody: PromptURL;
};

export type UploadGenerateUrlResponse = (ResponseURL);

export type UploadValidateUrlRouteData = {
    token: string;
};

export type UploadValidateUrlRouteResponse = (boolean);

export type UploadLoginAccessTokenData = {
    formData: Body_upload___login_access_token;
};

export type UploadLoginAccessTokenResponse = (Token);

export type UploadUploadFileData = {
    formData: Body_upload___upload_file;
};

export type UploadUploadFileResponse = (Message);