/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ValidateImport } from './routes/validate'
import { Route as InvalidUrlImport } from './routes/invalid-url'
import { Route as ErrorImport } from './routes/error'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ValidateRoute = ValidateImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => rootRoute,
} as any)

const InvalidUrlRoute = InvalidUrlImport.update({
  id: '/invalid-url',
  path: '/invalid-url',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/invalid-url': {
      id: '/invalid-url'
      path: '/invalid-url'
      fullPath: '/invalid-url'
      preLoaderRoute: typeof InvalidUrlImport
      parentRoute: typeof rootRoute
    }
    '/validate': {
      id: '/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof ValidateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/invalid-url': typeof InvalidUrlRoute
  '/validate': typeof ValidateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/invalid-url': typeof InvalidUrlRoute
  '/validate': typeof ValidateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/invalid-url': typeof InvalidUrlRoute
  '/validate': typeof ValidateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/error' | '/invalid-url' | '/validate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/error' | '/invalid-url' | '/validate'
  id: '__root__' | '/' | '/error' | '/invalid-url' | '/validate'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorRoute: typeof ErrorRoute
  InvalidUrlRoute: typeof InvalidUrlRoute
  ValidateRoute: typeof ValidateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorRoute: ErrorRoute,
  InvalidUrlRoute: InvalidUrlRoute,
  ValidateRoute: ValidateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/error",
        "/invalid-url",
        "/validate"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/invalid-url": {
      "filePath": "invalid-url.tsx"
    },
    "/validate": {
      "filePath": "validate.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
