name: Test on push

on:
  push:
    paths:
      - "backend/**" # Only run when files in the backend directory change
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Specify your Python version

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: backend

      - name: Test the push
        run: pytest
        working-directory: backend
