name: Test on push

on:
  push:
    paths:
      - "backend/**" # Only run when files in the backend directory change

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Specify your Python version

      - name: Install dependencies
        run: |
          cd backend  # Change to the backend directory
          pip install -r requirements.txt

      - name: Test the push
        run: |
          cd backend  # Change to the backend directory again
          pytest
